### ISSUE TITLE
cannot start bash

### ISSUE THREAD

**Issue by matthias-k** [bethgelab/docker#4] opened 2016-07-18 14:36 UTC
I am trying to start our deeplearning container with a shell. However, when I run

```
GPU=0 ./agmb-docker run -d bethgelab/jupyter-deeplearning:cuda7.5-cudnn4  /bin/bash
```

`agmb-docker` seems to interpret `/bin/bash` as image name and starts the notebook anyway:

```
gpu8:Saliency/DeepGaze% GPU=0 ./agmb-docker run -d bethgelab/jupyter-deeplearning:cuda7.5-cudnn4  /bin/bash                                                                                               
Error: No such image or container: /bin/bash
[ NVIDIA ] =INFO= Not a CUDA image, nothing to be done


* Setting user name to:             mkuemmerer
* Setting user ID to:               4766
* Setting user groups to:           bethgelab:1019,cin:1011,sudo
* Setting password to:              pw
* Setting SSH port binding to:      56209 (to set manually add -p 56209:22 as flag)
* Setting Notebook port binding to: 664 (to set manually add -p 664:8888 as flag)

You can now open the notebook on the host machine by directing your browser to

    http://localhost:664

or, from a remote system, to

Device "eth0" does not exist.
    http://:664

In the latter case make sure that your local machine can see the server! Otherwise you might have to configure an SSH tunnel first.
```

I tried to fix this in the `agmb-docker`-script, however my bash knowledge is not that great. Does anyone have an idea? I think the script already parses the `-d` parameter, thus it should be possible to get the real image.

**Comment by matthias-k** [comment] 2016-07-19 11:56
Okay, I think I missunderstood how to use the docker container. I guess the intended way to get a shell is to start the container with `agmb-docker` and then either ssh into the container or use `docker exec -it container_name bash` (the latter one gives you a root shell, though).

**Comment by matthias-k** [comment] 2017-01-12 13:02
After a discussion with Wieland we decided to repopen this issue since it would be very helpful to be able to start our containers directly with an command (e.g. this could reduce the number of idling containers).

**Comment by wielandbrendel** [comment] 2017-01-12 21:04
The problem is basically fixed with the last rewrite of the agmb-docker script. Note that the above command should have been

`GPU=0 ./agmb-docker run -it bethgelab/jupyter-deeplearning:cuda8.0-cudnn5  /bin/bash`

(interactive + tty instead of detached). The only caveat is that you have to escape strings. For example, instead of

`./agmb-docker run bethgelab/jupyter-deeplearning:cuda8.0-cudnn5  /bin/echo 'Hello World'`

you have to write

`./agmb-docker run bethgelab/jupyter-deeplearning:cuda8.0-cudnn5  /bin/echo "'Hello World'"`

**Closed as completed by wielandbrendel** 2017-01-12 21:04 UTC
